import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import type { Metadata } from "next";

import AOSInit from "./aos-init";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Karla:ital,wght@0,200..800;1,200..800&family=Rowdies:wght@300;400;700&display=swap" rel="stylesheet" />
      </head>
      <body>
        <AOSInit />
        {children}
      </body>
    </html>
  );
}
